### ISSUE TITLE
Video compatibility

### ISSUE THREAD

**Issue by brianp** [cloudacy/native_exif#18]
Hey! I've been trying to use the exif reader with video but having no luck.
I've tried with multiple mp4 files, and some mov files.

It works fine with images I've tested with. Is it for images only?

The error I get is:
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(READ_ERROR, Error while reading metadata from source, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      Exif.getAttributes (package:native_exif/native_exif.dart:54:20)
```

**Comment by brianp** [comment]
Makes sense. Thanks for the confirmation. I was trying to get access to apples "created at" metadata. I don't know how they store it. But yeah a note in the readme that it's for images only would probably be good :D

Cheers!
